//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo.Client.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDo.Client.Shared.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        internal static string CategoryList_AddCategoryBtn {
            get {
                return ResourceManager.GetString("CategoryList_AddCategoryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Dashboard_MainMenu_CategoriesBtn {
            get {
                return ResourceManager.GetString("Dashboard_MainMenu_CategoriesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Dashboard_MainMenu_TasksBtn {
            get {
                return ResourceManager.GetString("Dashboard_MainMenu_TasksBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, {0}.
        /// </summary>
        internal static string Dashboard_TopBar_UserName {
            get {
                return ResourceManager.GetString("Dashboard_TopBar_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Forms_AddBtn {
            get {
                return ResourceManager.GetString("Forms_AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Forms_CancelBtn {
            get {
                return ResourceManager.GetString("Forms_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Forms_SaveBtn {
            get {
                return ResourceManager.GetString("Forms_SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        internal static string Login_GreetingsTitle {
            get {
                return ResourceManager.GetString("Login_GreetingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with GitHub.
        /// </summary>
        internal static string Login_LoginBtn {
            get {
                return ResourceManager.GetString("Login_LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string NewCategoryDialog_Form_ColorInput {
            get {
                return ResourceManager.GetString("NewCategoryDialog_Form_ColorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NewCategoryDialog_Form_NameInput {
            get {
                return ResourceManager.GetString("NewCategoryDialog_Form_NameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add category.
        /// </summary>
        internal static string NewCategoryDialog_Title {
            get {
                return ResourceManager.GetString("NewCategoryDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string NewTaskDialog_Form_CategoryInput {
            get {
                return ResourceManager.GetString("NewTaskDialog_Form_CategoryInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string NewTaskDialog_Form_DescriptionInput {
            get {
                return ResourceManager.GetString("NewTaskDialog_Form_DescriptionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string NewTaskDialog_Form_TitleInput {
            get {
                return ResourceManager.GetString("NewTaskDialog_Form_TitleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add task.
        /// </summary>
        internal static string NewTaskDialog_Title {
            get {
                return ResourceManager.GetString("NewTaskDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Task_Status_Done {
            get {
                return ResourceManager.GetString("Task_Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        internal static string Task_Status_InProgress {
            get {
                return ResourceManager.GetString("Task_Status_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Do.
        /// </summary>
        internal static string Task_Status_ToDo {
            get {
                return ResourceManager.GetString("Task_Status_ToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add task.
        /// </summary>
        internal static string TasksList_AddTaskBtn {
            get {
                return ResourceManager.GetString("TasksList_AddTaskBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks in category:.
        /// </summary>
        internal static string TasksList_CategoryNameLabel {
            get {
                return ResourceManager.GetString("TasksList_CategoryNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show done tasks.
        /// </summary>
        internal static string TasksList_ShowDoneTasksToggle {
            get {
                return ResourceManager.GetString("TasksList_ShowDoneTasksToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string UpdateCategoryDialog_Form_ColorInput {
            get {
                return ResourceManager.GetString("UpdateCategoryDialog_Form_ColorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UpdateCategoryDialog_Form_NameInput {
            get {
                return ResourceManager.GetString("UpdateCategoryDialog_Form_NameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update category.
        /// </summary>
        internal static string UpdateCategoryDialog_Title {
            get {
                return ResourceManager.GetString("UpdateCategoryDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string UpdateTaskDialog_Form_CategoryInput {
            get {
                return ResourceManager.GetString("UpdateTaskDialog_Form_CategoryInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string UpdateTaskDialog_Form_DescriptionInput {
            get {
                return ResourceManager.GetString("UpdateTaskDialog_Form_DescriptionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string UpdateTaskDialog_Form_TitleInput {
            get {
                return ResourceManager.GetString("UpdateTaskDialog_Form_TitleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update task.
        /// </summary>
        internal static string UpdateTaskDialog_Title {
            get {
                return ResourceManager.GetString("UpdateTaskDialog_Title", resourceCulture);
            }
        }
    }
}
